[toolchain]
anchor_version = "0.30.1" 

[features]
resolution = true
skip-lint = false

[programs.devnet]
nft_ticket = "GVpt8Jt7ZeRNccwBThid9eiPRquDP1KiQHs3n3ADdbYn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


[test]
startup_wait = 70000
shutdown_wait = 4000

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
# [[test.genesis]]
# address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
# program = "tests/metaplex_token_metadata_program.so"
